# Generated by Django 4.1.7 on 2023-03-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagueApp', '0003_team_goal_difference_team_goals_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='goals',
            field=models.IntegerField(default=0),
        ),
    ]
